// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3hOvcEEizmhe8dBtn2wMgqR7Xro9LVTk',
    appId: '1:414106673796:web:b4a361dc3eb3dbb83bd8d1',
    messagingSenderId: '414106673796',
    projectId: 'felix-4e1f0',
    authDomain: 'felix-4e1f0.firebaseapp.com',
    storageBucket: 'felix-4e1f0.appspot.com',
    measurementId: 'G-E00VWV5T5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV7SALbuqATltaCqJkQS6A5fj8tmztiCc',
    appId: '1:414106673796:android:7f195a44752f43113bd8d1',
    messagingSenderId: '414106673796',
    projectId: 'felix-4e1f0',
    storageBucket: 'felix-4e1f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2kDQDqJ-yD6esB8c_TRk6Dx2ifpVY7aI',
    appId: '1:414106673796:ios:5c225423a82c0cd33bd8d1',
    messagingSenderId: '414106673796',
    projectId: 'felix-4e1f0',
    storageBucket: 'felix-4e1f0.appspot.com',
    iosBundleId: 'com.example.felix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2kDQDqJ-yD6esB8c_TRk6Dx2ifpVY7aI',
    appId: '1:414106673796:ios:6b7a530396d629543bd8d1',
    messagingSenderId: '414106673796',
    projectId: 'felix-4e1f0',
    storageBucket: 'felix-4e1f0.appspot.com',
    iosBundleId: 'com.example.felix.RunnerTests',
  );
}
